base_url = "zymologia.fi"
compile_sass = true
title = "Alzymologist Oy"
description = "Laboratory services for microbrewers"
generate_feed = true

[extra]
hyde_sticky = true
hyde_reverse = false
hyde_theme = ""
hyde_links = [
    {url = "mailto:contact@zymologia.fi", name = "Contact us"},
    {url = "/info/services#starthere", name = "Services"},
    {url = "/info/methods#starthere", name = "Capabilities"},
    {url = "/info/pricing#starthere", name = "Pricing"},
    {url = "/#starthere", name = "Blog"},
    {url = "/info/about#starthere", name = "About"},
    {url = "/info/gdpr#starthere", name = "Privacy policy"},
    {url = "atom.xml", name = "Atom feed"},
]
